### ISSUE TITLE
[공지] 학회 질의응답/소통 게시판

### ISSUE THREAD

**Issue by qkrdmswl** [MJU-Coin/Coin_Notice#1]
### 이곳은 학회원들과 다양한 소통이 이루어지는 게시판입니다!
+ 학회 공지사항 문의 🗯
+ 학회 일정 문의 💬
+ 학회원들과 소통 🖐
+ 그 외 건의사항 🙋‍♀️

#### 공지를 확인 후, 댓글로 "학번 이름 확인했습니다"를 댓글로 달아주세요 ✔
+ ex) 20 박은지 확인했습니다

**Comment by qkrdmswl** [comment]
20 박은지 확인했습니다

**Comment by dojinyou** [comment]
19 유도진 확인했습니다!
